GET http://localhost:3000/test

###
GET http://localhost:3000/spots

###
GET http://localhost:3000/spots/5
###
DELETE http://localhost:3000/spots/5
###
POST http://localhost:3000/spots

Content-Type: application/json
{
  "foto": "hallo.jpg",
  "titel": "testitel",
  "beschreibung":"testdesc",
  "rating": 4.5,
  "likes": 56,
  "added_by": "patricier" ,
  "latitude": 45.8990,
  "longitude":65.3234
}